### ISSUE TITLE
32bit system incompatible

### ISSUE THREAD

**Issue by YoungFaithful** [holgerteichgraeber/ClustForOpt.jl#78]
explicit `Int64` and `Float64` statements lead to Errors on 32bit systems

**Comment by YoungFaithful** [comment]
`AbstractFloat` war Verschlimmbesserung
https://stackoverflow.com/questions/44729392/generic-float-type-in-julia-language
usage of `AbstractFloat` leads to errors that I didn't encouter on my system until the packages updated officially. Somehow restarting and recompiling CapacityExpansion didn't successfully include the changes in the depending package ClustForOpt in local testing and wasn't included in automated testing.

**Comment by holgerteichgraeber** [comment]
Ok, that makes sense. 
It seems that using `Float64` will do just fine, how about changing all `AbstractFloat` to `Float64`. I assume the issue that arose with the user came from `Int64`, and that's handled by using `Int` now.

From the link you sent:
> (+1) Nicely answered @LyndonWhite, so what I understood is, and correct me if I'm wrong, writing Float64 will work just fine on 32-bit systems? My big concern is writing generic code that is also performant. BTW, Julia has a great community, it's my honor to be one of them. – AboAmmar Jun 24 '17 at 18:01
you are correct Float64 will work fine on 32 bit systems. – Lyndon White Jun 24 '17 at 23:22

**Comment by holgerteichgraeber** [comment]
closed with #80
