### ISSUE TITLE
test cases without CapacityExpansion.jl dependency

### ISSUE THREAD

**Issue by holgerteichgraeber** [holgerteichgraeber/ClustForOpt.jl#85]
Let's write the test cases such that it is not dependent on capacity expansion, because that dependency makes tests fail whenever we update ClustForOpt with breaking changes.

**Comment by YoungFaithful** [comment]
If we don't include the CEP tests, we might oversee breaking changes without intending them.

**Comment by holgerteichgraeber** [comment]
I agree that it should be part of the workflow. If CEP is part of the tests though, the tests will always fail if there is a breaking change, because CEP hasn't been updated for these changes yet. 

If it is tested upstream in CEP itself, we will find the breaking changes through that as well. The test cases in clustForOpt should be complete enough (which they are not yet) to cover the things that are relevant to CEP without using the package itself.

**Comment by YoungFaithful** [comment]
Okay. Sounds good.

**Comment by holgerteichgraeber** [comment]
#84 taken out CapacityExpansion test cases and replaced by a simple case if load_data and run_clust works. Will need to write more detailed test cases in the future that tests a broad spectrum of the functionality though.
