### ISSUE TITLE
Unable to implement example

### ISSUE THREAD

**Issue by Deepakgthomas** [holgerteichgraeber/ClustForOpt.jl#95]
Hello,

I am trying to test the ClustForOpt.jl software, however when I try running a variation of the example provided in the readme -

using ClustForOpt
ts_input_data = load_timeseries_data("DAM", "GER")

I get the following error: 
MethodError: no method matching load_timeseries_data(::String, ::String)
Closest candidates are:
  load_timeseries_data(::Any; region, T, years, att) at /home/nvidia/.julia/packages/ClustForOpt/YNrmS/src/utils/load_data.jl:19

Stacktrace:
 [1] top-level scope at In[38]:2

**Comment by holgerteichgraeber** [comment]
Thank you for testing ClustForOpt, and thank you for pointing that out! 
The example seems to be an old version of load_timeseries_data(). 
See [workflow_introduction.jl](https://github.com/holgerteichgraeber/ClustForOpt.jl/blob/master/examples/workflow_introduction.jl) for a working example. 

I am currently rewriting the documentation and README, the `documentation` branch has the newest version. I hope it should be up in `dev` and `master` in 1-2 weeks. Have a look if you like to see hopefully improved descriptions of how to use ClustForOpt.jl. Feedback welcome anytime. 
In the `documentation` branch, there is also a new function to load_timeseries_data() where you just specify the data import by saying for example `load_timeseries_data(:CEP_GER1)`.

**Comment by Deepakgthomas** [comment]
Thank you for the quick information :)

**Comment by holgerteichgraeber** [comment]
@Deepakgthomas  the new documentation and also the load_timeseries_data() function is now in the current stable version of ClustForOpt.
